CREATE DATABASE IF NOT EXISTS 
bd_controle_financeiro;
USE bd_controle_financeiro;

CREATE TABLE USUARIO(
	ID_USUARIO INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOME_USUARIO VARCHAR(15),
	USER_NAME VARCHAR(5),
	SENHA VARCHAR(50)
);

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOME_CATEGORIA VARCHAR(15),
	ID_AUTOR INT(6)
);


CREATE TABLE RECEITA(
	ID_RECEITA INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(15),
	DATA DATETIME,
	VALOR FLOAT,
	ID_AUTOR INT(6)
);

CREATE TABLE DESPESA(
	ID_DESPESA INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT(6),
	DATA DATETIME,
	DESCRICAO VARCHAR(15),
	ID_CATEGORIA INT(6),
	VALOR FLOAT,
	FORMA_PAGAMENTO INT(6),
	ID_CARTAO INT(6)
);

CREATE TABLE CARTAO(
	ID_CARTAO INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT(6),
	TIPO VARCHAR(15),
	ID_BANDEIRA INT(6),
	DESCRICAO VARCHAR(15),
	DIGITO_FINAL INT(4)
);

CREATE TABLE BANDEIRA_CARTAO(
	ID_BANDEIRA INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOME_BANDEIRA VARCHAR(15)
);

INSERT INTO BANDEIRA_CARTAO VALUES(1,'MASTERCARD');
INSERT INTO BANDEIRA_CARTAO VALUES(2,'VISA');
INSERT INTO BANDEIRA_CARTAO VALUES(3,'HIPERCARD');
INSERT INTO BANDEIRA_CARTAO VALUES(4,'ALELO');
INSERT INTO BANDEIRA_CARTAO VALUES(5,'ELO');
INSERT INTO BANDEIRA_CARTAO VALUES(6,'TICKET');

CREATE TABLE BALANCO(
	ID_BALANCO INT(6) PRIMARY KEY,
	ID_USUARIO INT(6),
	VALOR_FINAL FLOAT
);
